name: Build

on: [push, pull_request]

jobs:
  build:
    env:
      TEST_TIMEOUT_MINUTES: 20
    timeout-minutes: 20 # we have a locking issue, so cap the runs at ~20m to account for varying build times, etc
    strategy:
      matrix:
        os: [windows-2022, macos-11, ubuntu-20.04]
        dotnet: [6.0.200]
      fail-fast: false # we have timing issues on some OS, so we want them all to run

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Fix windows pagefile issues
      uses: al-cheb/configure-pagefile-action@v1.2
      if: ${{ matrix.os == 'windows-2019' }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore tools
      run: dotnet tool restore
    - name: Run Build
      run: dotnet fake build -t Build

    - name: Run and report tests
      uses: zyborg/dotnet-tests-report@v1
      with:
        project_path: test/FsAutoComplete.Tests.Lsp
        no_restore: true # we just did the build/restore above
        msbuild_configuration: Release # we do the tests against the release build
        github_token: ${{ secrets.FSAC_CHECKS_TOKEN }}
        set_check_status_from_test_outcome: true
        fail_build_on_failed_tests: true
        extra_test_parameters: "--no-build --logger GitHubActions /p:AltCover=true /p:AltCoverAssemblyExcludeFilter=System.Reactive|FSharp.Compiler.Service|Ionide.ProjInfo|FSharp.Analyzers|Analyzer|Humanizer|FSharp.Core|Dapper|FSharp.DependencyManager"
        skip_check_run: true # something's wrong with the PAT used above, so github checks won't be added
      env:
        TEST_TIMEOUT_MINUTES: 10
