name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2

      - name: Restore tools
        run: dotnet tool restore

      - name: Run Build
        run: dotnet fake build -t Release

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v1.1.0
        with:
          version: ${{ github.ref }}
          path: ./CHANGELOG.md

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: bin/pkgs/*
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.changelog_reader.outputs.log_entry }}

      - name: Push packages
        run: dotnet nuget push bin/pkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_KEY }}
