name: Release

on:
  workflow_dispatch:
    inputs:
      username:
        description: Github username of the person triggering the release
        default: "Krzysztof-Cieslak"
        required: true
      email:
        description: Email of the person triggering the release
        default: "krzysztof_cieslak@windowslive.com"
        required: true

jobs:
  release:
    strategy:
      matrix:
        dotnet: [5.0.301]

    runs-on: ubuntu-20.04

    steps:
    # manual triggers are detached HEADs, so we need to checkout the branch
    # to actually create + push a commit later on in the workflow
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore tools
      run: dotnet tool restore
    - name: Run Build
      run: dotnet fake build -t Build
    - name: Publish Release
      env:
        nuget-key: ${{ secrets.NUGET_KEY }}
        github-token: ${{ secrets.FSAC_CHECKS_TOKEN }}
        github-user: ${{ github.event.inputs.username }}
        user-email: ${{ github.event.inputs.email }}
      run: dotnet fake build -t Release
